CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE niveau AS ENUM('A1', 'A2', 'B1', 'B2', 'C1');
CREATE TYPE wordType AS ENUM ('Verb', 'Adjektiv', 'Nomen', 'Adverb', 'Pronomen', 'Konjunktion', 'Präposition');

CREATE TABLE vocabulary (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    de_word VARCHAR(30) NOT NULL,
    fa_word VARCHAR(30) NOT NULL,
    niveau niveau,
    wordType wordType
);

INSERT INTO vocabulary (de_word, fa_word, niveau, wordType) VALUES
('ankommen', 'رسیدن', 'A2', 'Verb'),
('abholen', 'برداشتن / تحویل گرفتن', 'A2', 'Verb'),
('bequem', 'راحت', 'A2', 'Adjektiv'),
('besonders', 'به ویژه', 'A2', 'Adverb'),
('erklären', 'توضیح دادن', 'A2', 'Verb'),
('fühlen', 'احساس کردن', 'A2', 'Verb'),
('gefallen', 'پسندیدن', 'A2', 'Verb'),
('gewinnen', 'برنده شدن', 'A2', 'Verb'),
('hoffentlich', 'ان‌شاءالله / امیدوارم', 'A2', 'Adverb'),
('verpassen', 'از دست دادن', 'A2', 'Verb'),
('abschließen', 'قفل کردن / به پایان رساندن', 'A2', 'Verb'),
('anmelden', 'ثبت‌نام کردن', 'A2', 'Verb'),
('ausfüllen', 'پر کردن', 'A2', 'Verb'),
('beenden', 'تمام کردن', 'A2', 'Verb'),
('bestellen', 'سفارش دادن', 'A2', 'Verb'),
('bezahlen', 'پرداخت کردن', 'A2', 'Verb'),
('bieten', 'پیشنهاد دادن', 'A2', 'Verb'),
('brauchen', 'نیاز داشتن', 'A2', 'Verb'),
('dauern', 'طول کشیدن', 'A2', 'Verb'),
('entscheiden', 'تصمیم گرفتن', 'A2', 'Verb'),
('entschuldigen', 'ببخشید / عذرخواهی کردن', 'A2', 'Verb'),
('erreichen', 'رسیدن به / دست یافتن', 'A2', 'Verb'),
('erwarten', 'انتظار داشتن', 'A2', 'Verb'),
('fehlen', 'کمبود داشتن / دلتنگ بودن', 'A2', 'Verb'),
('folgen', 'دنبال کردن', 'A2', 'Verb'),
('fotografieren', 'عکس گرفتن', 'A2', 'Verb'),
('funktionieren', 'کار کردن (وسیله)', 'A2', 'Verb'),
('geboren', 'به دنیا آمده', 'A2', 'Adjektiv'),
('gehören', 'متعلق بودن به', 'A2', 'Verb'),
('genießen', 'لذت بردن', 'A2', 'Verb'),
('geschehen', 'اتفاق افتادن', 'A2', 'Verb'),
('gründen', 'تأسیس کردن', 'A2', 'Verb'),
('heiraten', 'ازدواج کردن', 'A2', 'Verb'),
('hoffen', 'امیدوار بودن', 'A2', 'Verb'),
('interessieren', 'علاقه‌مند کردن', 'A2', 'Verb'),
('klingeln', 'زنگ زدن', 'A2', 'Verb'),
('kriegen', 'گرفتن / دریافت کردن', 'A2', 'Verb'),
('lächeln', 'لبخند زدن', 'A2', 'Verb'),
('leihen', 'قرض دادن / گرفتن', 'A2', 'Verb'),
('melden', 'اطلاع دادن / گزارش کردن', 'A2', 'Verb'),
('merken', 'متوجه شدن / به خاطر سپردن', 'A2', 'Verb'),
('mieten', 'اجاره کردن', 'A2', 'Verb'),
('mitnehmen', 'همراه بردن', 'A2', 'Verb'),
('prüfen', 'بررسی کردن / امتحان گرفتن', 'A2', 'Verb'),
('schaffen', 'موفق شدن / انجام دادن', 'A2', 'Verb'),
('schicken', 'ارسال کردن', 'A2', 'Verb'),
('sich beeilen', 'عجله کردن', 'A2', 'Verb'),
('sich erinnern', 'به یاد آوردن', 'A2', 'Verb'),
('sich freuen', 'خوشحال شدن', 'A2', 'Verb'),
('sich interessieren', 'علاقه داشتن', 'A2', 'Verb'),
('teilnehmen', 'شرکت کردن', 'A2', 'Verb'),
('umziehen', 'اسباب‌کشی کردن / لباس عوض کردن', 'A2', 'Verb'),
('unterschreiben', 'امضا کردن', 'A2', 'Verb'),
('verbessern', 'بهبود دادن', 'A2', 'Verb'),
('vergessen', 'فراموش کردن', 'A2', 'Verb'),
('verlieren', 'گم کردن / باختن', 'A2', 'Verb'),
('versuchen', 'امتحان کردن / تلاش کردن', 'A2', 'Verb'),
('vorbereiten', 'آماده کردن', 'A2', 'Verb'),
('warten', 'منتظر ماندن', 'A2', 'Verb'),
('wiederholen', 'تکرار کردن', 'A2', 'Verb'),
('wünschen', 'آرزو کردن', 'A2', 'Verb'),
('zeigen', 'نشان دادن', 'A2', 'Verb'),
('zuhören', 'گوش دادن', 'A2', 'Verb'),
('zumachen', 'بستن', 'A2', 'Verb'),
('zustimmen', 'موافقت کردن', 'A2', 'Verb');
